# Generated by Django 4.2 on 2023-12-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_productimage_productimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='iamge',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
